name: Build and Deploy Java App to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: MathSolver
  AZURE_WEBAPP_PACKAGE_PATH: '${{ github.workspace }}/MathSolver/target'
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'zulu'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Set up JDK ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: 'Build with Maven'
        run: mvn clean install -DskipTests
        working-directory: ./MathSolver

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/*.jar