name: Build and Deploy Java App to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: MathSolver      # Replace with your Azure Web App name
  JAVA_VERSION: '17'                 # Azure App Service supports Java 17 LTS
  JAVA_DISTRIBUTION: 'temurin'       # Eclipse Temurin is a good choice

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Set up JDK ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: 'Build with Maven'
        run: mvn clean package -DskipTests

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ github.workspace }}/target/*.jar'